Rotas disponíveis:
{'GET', 'OPTIONS', 'HEAD'} /static/<path:filename>
{'GET', 'OPTIONS', 'HEAD'} /colaborador/todos-colaboradores
{'POST', 'OPTIONS'} /colaborador/cadastrar
{'PUT', 'OPTIONS'} /colaborador/atualizar/<int:id_colaborador>
{'POST', 'OPTIONS'} /colaborador/login
{'DELETE', 'OPTIONS'} /reembolso/linha/<int:linha_id>
{'POST', 'OPTIONS'} /reembolso/enviar/<int:reembolso_id>
{'POST', 'OPTIONS'} /reembolso/cancelar/<int:reembolso_id>
{'POST', 'OPTIONS'} /reembolso/criar-tabelas
{'GET', 'OPTIONS', 'HEAD'} /flasgger_static/<path:filename>
{'GET', 'OPTIONS', 'HEAD'} /apidocs/
{'GET', 'OPTIONS', 'HEAD'} /oauth2-redirect.html
{'GET', 'OPTIONS', 'HEAD'} /apidocs/index.html
{'GET', 'OPTIONS', 'HEAD'} /apispec.json/
Traceback (most recent call last):
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\run.py", line 5, in <module>
    app = create_app()
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\src\app.py", line 44, in create_app
    db.create_all() #Cria as tabelas caso elas não existam
    ~~~~~~~~~~~~~^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\flask_sqlalchemy\extension.py", line 900, in create_all
    self._call_for_binds(bind_key, "create_all")
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\flask_sqlalchemy\extension.py", line 881, in _call_for_binds
    getattr(metadata, op_name)(bind=engine)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5925, in create_all
    bind._run_ddl_visitor(
    ~~~~~~~~~~~~~~~~~~~~~^
        ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3248, in _run_ddl_visitor
    with self.begin() as conn:
         ~~~~~~~~~~^^
  File "C:\Users\adria\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3238, in begin
    with self.connect() as conn:
         ~~~~~~~~~~~~^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3274, in connect
    return self._connection_cls(self)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3298, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout
    rec = pool._do_get()
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 675, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\pymysql\connections.py", line 979, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\pymysql\_auth.py", line 267, in caching_sha2_password_auth
    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
  File "C:\Users\adria\Desktop\vnw\challenge03-Vai-Na-Web\Projeto-SISPAR\BACKEND\api\venv\Lib\site-packages\pymysql\_auth.py", line 144, in sha2_rsa_encrypt
    raise RuntimeError(
    ...<2 lines>...
    )
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
